/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.15
 * Generated at: 2015-11-30 14:22:55 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.IPPS;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Calendar;
import servlet.O_DataDetails;
import servlet.F_Function;

public final class details_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("    <title>Data Details</title>\n");
      out.write("  ");

    if(session.getAttribute("user")==null || session.getAttribute("user").toString().trim().equals("")) {response.sendRedirect("/login");}
      F_Function FF = new F_Function();
      SimpleDateFormat date = new SimpleDateFormat("yyyy-MM-dd hh:mm:ss");
      Date dt = new Date();
      Calendar cal = Calendar.getInstance();
      String tglnye = date.format(dt);
    String exportToExcel = request.getParameter("exportToExcel");
    if (exportToExcel != null
            && exportToExcel.toString().equalsIgnoreCase("true")) {
      response.setContentType("application/vnd.ms-excel");
      response.setHeader("Content-Disposition", "inline; filename="
              + "Details "+tglnye+".xls");
    }
    O_DataDetails Data = FF.DataDetails(session.getAttribute("level").toString());
    String[] Desc = {"SPARE PARTS", "SERVICE (LABOUR)/SMC", "FULL MAINTENANCE CONTRACT/FMS", "REVENUE", "COST OF SALES (SPARE PARTS)", "COST OF SALES (SERVICE)", "- Periodic Maintenance", "- Part Repair", "- Part R & I", "- Component", "- GET & Undercarriage Group", "-Warranty & Campaign", "- Consumable", "TOTAL COGS", "GROSS PROFIT", "EXPENSES", "- Employee Expenses", "- Asset Depreciation", "- Operation Expenses", "OPR. PROFIT", "PROFIT % OF SALES"};
  
      out.write("\n");
      out.write("\n");
      out.write("  <!-- Bootstrap Core CSS -->\n");
      out.write("  <link href=\"../bower_components/bootstrap/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<h3>PT. INTRACO PENTA PRIMA SERVIS</h3>\n");
      out.write("<h3>CSA GOLD FINANCIAL REPORT TAHUN ");
      out.print(cal.get(Calendar.YEAR));
      out.write("</h3>\n");
      out.write("<h3>CSA PROFITABILITY REPORT ");
      out.print(cal.get(Calendar.YEAR));
      out.write(" (In thousand IDR)</h3>\n");
      out.write("<br>\n");
      out.write("<table border=\"0\" >\n");
      out.write("\n");
      out.write("  <tr>\n");
      out.write("    <td>\n");
      out.write("\n");
      out.write("      <table border=\"1\" class=\"text-nowrap\">\n");
      out.write("        <tr>\n");
      out.write("          <th rowspan=\"2\">PROJECT</th>\n");
      out.write("          <th rowspan=\"2\">DESCRIPTION</th>\n");
      out.write("          <td colspan=\"3\" align=\"center\">TOTAL</td>\n");
      out.write("        </tr>\n");
      out.write("        <tr>\n");
      out.write("          <td>TARGET</td>\n");
      out.write("          <td>ACTUAL</td>\n");
      out.write("          <td>%</td>\n");
      out.write("        </tr>\n");
      out.write("\n");
      out.write("        <tr>\n");
      out.write("          <th rowspan=\"21\">");
      out.print("project");
      out.write("</th>\n");
      out.write("          <td height=\"100%\">");
      out.print(Desc[0]);
      out.write("</td>\n");
      out.write("        </tr>\n");
      out.write("        ");
for (int desc=1;desc<Desc.length;desc++){
          out.println("<tr><td>"+Desc[desc]+"</td></tr>");
        }
        
      out.write("\n");
      out.write("      </table>\n");
      out.write("\n");
      out.write("    </td>\n");
      out.write("    ");
for (int bulan=0;bulan<11;bulan++){
      out.write("\n");
      out.write("    <td>\n");
      out.write("      <table border=\"1\">\n");
      out.write("        <tr>\n");
      out.write("          <td colspan=\"2\" align=\"center\">");
      out.print(bulan);
      out.write("</td>\n");
      out.write("        </tr>\n");
      out.write("        <tr>\n");
      out.write("          <td>TARGET</td>\n");
      out.write("          <td>ACTUAL</td>\n");
      out.write("        </tr>\n");
      out.write("        ");

            for (int desc=0;desc<Desc.length;desc++){
              out.println("<tr><td>"+"nilaiTarget"+"</td><td>"+"nilaiActual"+"</td></tr>");
            }
        
      out.write("\n");
      out.write("      </table>\n");
      out.write("\n");
      out.write("    </td>\n");
      out.write("    ");
}
    
      out.write("\n");
      out.write("\n");
      out.write("  </tr>\n");
      out.write("  <tr>\n");
      out.write("    <td>\n");
      out.write("\n");
      out.write("      <table border=\"1\" class=\"text-nowrap\">\n");
      out.write("        <tr>\n");
      out.write("          <th rowspan=\"2\">PROJECT</th>\n");
      out.write("          <th rowspan=\"2\">DESCRIPTION</th>\n");
      out.write("          <td colspan=\"3\" align=\"center\">TOTAL</td>\n");
      out.write("        </tr>\n");
      out.write("        <tr>\n");
      out.write("          <td>TARGET</td>\n");
      out.write("          <td>ACTUAL</td>\n");
      out.write("          <td>%</td>\n");
      out.write("        </tr>\n");
      out.write("\n");
      out.write("        <tr>\n");
      out.write("          <th rowspan=\"21\">");
      out.print("project");
      out.write("</th>\n");
      out.write("          <td height=\"100%\">");
      out.print(Desc[0]);
      out.write("</td>\n");
      out.write("        </tr>\n");
      out.write("        ");
for (int desc=1;desc<Desc.length;desc++){
          out.println("<tr><td>"+Desc[desc]+"</td></tr>");
        }
        
      out.write("\n");
      out.write("      </table>\n");
      out.write("\n");
      out.write("    </td>\n");
      out.write("    ");
for (int bulan=0;bulan<11;bulan++){
      out.write("\n");
      out.write("    <td>\n");
      out.write("      <table border=\"1\">\n");
      out.write("        <tr>\n");
      out.write("          <td colspan=\"2\" align=\"center\">");
      out.print(bulan);
      out.write("</td>\n");
      out.write("        </tr>\n");
      out.write("        <tr>\n");
      out.write("          <td>TARGET</td>\n");
      out.write("          <td>ACTUAL</td>\n");
      out.write("        </tr>\n");
      out.write("        ");

          for (int desc=0;desc<Desc.length;desc++){
            out.println("<tr><td>"+"nilaiTarget"+"</td><td>"+"nilaiActual"+"</td></tr>");
          }
        
      out.write("\n");
      out.write("      </table>\n");
      out.write("\n");
      out.write("    </td>\n");
      out.write("    ");
}
    
      out.write("\n");
      out.write("\n");
      out.write("  </tr>\n");
      out.write("</table>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
